services:
  rewritable-new:
    build:
      context: ..
      dockerfile: service/Dockerfile
    image: ikangai/rewritable-new:latest
    container_name: rewritable-new
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-8080}:80"
